### ISSUE TITLE
Опис інсталяції локалізації.

### ISSUE THREAD

**Issue by Sentinas** [IndiMops/translate-Red-Deat-Redemption-2#10]
На поточний момент цей опис можна суттєво скоротити.
Свіжа версія  RDR 2 Asi Loader 0.2.2 вже не включає в себе ніяких папок. Там один файл version.dll яки треба скопіювати в теку гри.
Пункт: Але слід відкрити "Lenny's Mod Loader", який ми перемістили з архіву...." включно з скріном можна прибрати.

Дякую що взялися за такий проект. Зважаючи на те що переклад ще не повністю відредагований до поточного прогресу, виглядає і сприймається гра рідною мовою просто неймовірно. Буду проходити по мірі оновлення локалізації. :)

**Comment by Sentinas** [comment]
І до речі. Рекомендую зробити посібник в Steam з описом інсталяції та поточним прогресом. Бо навіть не подумав що вже існує локалізація, якби в твітері не побачив тред. А вже пізніше знайшов за допомогою гугла.

**Comment by IndiMops** [comment]
Ну, я не шарую за модинг в іграх Рокстар. Я створив це типу мод, по прикладах з форумів, бо не знаю за lua та інші приблуди. Так, звісно є ще спосіб зі створенням теки `Replace`, але на мою думку людям буде важче це зрозуміти, але можливо я лише так думаю. Все ж ми в майбутньому плануємо створити інсталятор для встановлення локалізації, тому це зараз не нагально.

Так, сам знаю багато помилок, але переклад я збирався зробити для невеличкої групи друзів. А тут я вирішив випустити його тут на GitHub . Друг розказав другу, а він іншому і получилося сарафане радіо, що тепер про це знає майже, якщо не все українське ком'юніті РДР 2 і не тільки.

**Comment by Sentinas** [comment]
Я просто хотів сказати що опис інсталяції на зараз можна змінити (вирізати те що вже не актуально). Свіжа версія RDR 2 Asi Loader 0.2.2 в архів має всього ти файли (два текстових та длл). От саме длл просто копіюємо в теку з грою. Більше з Asi нічого робити не треба. Тобто трохи підправити інсталяцію.
Щодо перекладу, навіть з невеличкими одруківками він шикарний. Звісно хочеться більший відсоток перекладу, але я розумію що перекладати зовсім не просто. У самого за плечами декілька локалізацій ігор та навіть поточний проект.
Бажаю успіху та натхнення. І буду чекати оновлені версії :)
