### ISSUE TITLE
Долучення до перекладу

### ISSUE THREAD

**Issue by petersweet** [IndiMops/translate-Red-Deat-Redemption-2#11]
Вітаю!

Сподіваюсь ви та ваші близькі в безпеці на скільки це можливо. 

Маю бажання долучитись до перекладу і вже підтримав вас донатом. Займався локалізацією мобільних застосунків на топ країни протягом року. Також дослідив гру на предмет "country talk" та адаптації під наш сленг, а також активно перепроходжу її зараз з пошуком діалогів. 

Створив форк по зміні назв персонажів, а також написав вам у телеграм, проте не отримав відповіді.
Сподіваюсь на долучення до роботи)

Гарного дня!

**Comment by IndiMops** [comment]
Зараз вже не шукаємо перекладачів, але шукаємо редакторів, як ви ставитеся до цього?

**Comment by petersweet** [comment]
Вітаю, дякую за відповідь!
Так, звичайно, готовий долучитись до редагування - надішліть будь ласка інструкції та матеріали

**Comment by IndiMops** [comment]
Можете написати свій нікнейм, щоб я легше зміг вас знайти

**Comment by petersweet** [comment]
Вітаю нік, діскорду - Bread_Baker#5895
