### ISSUE TITLE
Помилка у прологу 

### ISSUE THREAD

**Issue by za5adlo** [IndiMops/translate-Red-Deat-Redemption-2#14]
Доброго дня і дуже вдячний за можливість пограти з українською локалізацію. 

Коли Датч розповідає Артуру що вони втратили Деві. Він говорить "втартили" замість "втратили".

Пізніше Датч говорить фразу (В нас є вогонб і кров) замість слова "вогонь".

Є помилка у прологу, коли Сєді Адлер розповідає Моргану та іншим за його чоловіка, вона говорить "чоловкі" замість "чоловік". Це коли вони виходять з її будинка. 

Вибачте за мову, якщо казав щось не зовсім верно.

У першому акті, коли Датч розповідає Артуру подробиці завдання (це перше завдання після рятування Джона від холоду та вовків, є слово "шороші" ( інформатори ) напевно замість "хороші"

**Comment by za5adlo** [comment]
я так розумію, що мені треба було шукати помилки у перекладі через сайт а ні у гри, для більшей допомоги, вибачте. я не зможу тому що я не зовсім розумію де там знайти хоча б розділ прологу. вибачте за час у таком разі. вибачте за мову ще раз, я ніколи її не вчив насправді.

**Comment by IndiMops** [comment]
> я так розумію, що мені треба було шукати помилки у перекладі через сайт а ні у гри, для більшей допомоги, вибачте. я не зможу тому що я не зовсім розумію де там знайти хоча б розділ прологу. вибачте за час у таком разі. вибачте за мову ще раз, я ніколи її не вчив насправді. ще раз дякую за можливість пограти хоча б частково укр мовою на даний момент.

Дякую, що написали. Ми знаємо, що там є такі помилки, бо цей розділ перекладався за пів дня швидкома. В наступних оновленнях вже можна буде побачити роботу редакторів, тому таких помилок вже не буде
