### ISSUE TITLE
російська

### ISSUE THREAD

**Issue by xvladqt** [IndiMops/translate-Red-Deat-Redemption-2#16]
![image](https://github.com/IndiMops/translate-Red-Deat-Redemption-2/assets/1107738/1b2caf7c-c41e-4eac-bece-eefc9142fe8d)
Зустрів отаке. Переклад робиться з російської ?

**Comment by IndiMops** [comment]
Дякую що помітили таке. Так робився, але ще коли я сам розбирався із технічною частиною на самому початку, коли ще не була зібрана команда. Зараз весь переклад ведеться виключно з англійської.
