### ISSUE TITLE
Допомога в перекладі

### ISSUE THREAD

**Issue by OverDemetrius** [IndiMops/translate-Red-Deat-Redemption-2#4]
Чи зможу я якось докласти зусиль та допомогти в перекладі RDR2 українською? Ознайомлений з усіма правилами нового правопису української мови та маю жагу до допомоги)

**Comment by IndiMops** [comment]
Приємно чути. Зв'яжіться зі мною ось [тут](https://t.me/indmops) чи [тут](https://discord.com/users/734082410504781854)
