### ISSUE TITLE
Допомога у перекладі

### ISSUE THREAD

**Issue by Keeach** [IndiMops/translate-Red-Deat-Redemption-2#6]
Дуже зацікавився після прочитаної статті про вашу ініціативу і маю бажання вам допомогти. Дуже радий що хтось насмілився взятись за таку гігантську роботу - українська душа потребує українських ковбоїв-козаків!

Я не редактор, і не професійний перекладач, але англійську знаю достатньо (маю надію на це) для того щоб допомоги Вам у перекладі. Просто для інформації - маю невеликий досвід в добровільному перекладі і правках оригінальних расєйских (вибачте) сабів для Alien: Isolation - моєму внутрішньому перфекціоністу стало нудно і він вирішив поекспериментувати з грою 😅 
Там було нескладно залізти - вони були окремими файлами у txt форматі.

В години коли буде світло і зв'язок у мене - чим зможу, тим і допоможу, з вашого дозволу, панове 💙💛 

P.S. мав сміливість почати виправляти - [коментарем](https://github.com/IndiMops/translate-Red-Deat-Redemption-2/commit/a6476506612e1880cf27542ab795d0f0f921d3f0#r97995335) на стрічці файлу. Я не знаю як вам зручніше, з гітхабом знайомий дуже поверхнево 😅

P.S.S. [Топ пасхалка](https://github.com/IndiMops/translate-Red-Deat-Redemption-2/commit/51c539345c1c993ca74848e3d2fff41095787999#r97995834) 🤣

**Comment by IndiMops** [comment]
Привіт, дякую за те що ви вже переглянули та написали деякі коментарі. Зв'яжіться зі мною ось [тут](https://t.me/indmops) чи [тут](https://discord.com/users/734082410504781854)
